[tox]
envlist = py{39}
recreate = True

[testenv]
basepython =
    py39: python3.9
deps =
    -r{toxinidir}/requirements.txt
    -r{toxinidir}/requirements-test.txt
commands = python -m howdou.tests {env:TESTNAME:}
